version: "3"
services:
  postgres:
    image: postgres:15-alpine
    environment:
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_USER=${DB_USER}
    ports:
    - "5432:5432"
    volumes:
    - ./.db/.db_data:/var/lib/postgresql/shopping-db
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "shoppingdb"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 0s  
  shopping-server:
    depends_on:
      postgres:
        condition: service_healthy
    image: shopping_app:latest
    network_mode: "host"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
