export enum ERR_CODE {
  NON_EXISINT_PRODUCT = 'NON_EXISING_PRODUCT',
  TOTAL_EXCEEDS_LIMIT = 'TOTAL_EXCEEDS_LIMIT',
  TOTAL_TOO_SMALL = 'TOTAL_TOO_SMALL',
  MALFORMED_DISCOUNT = 'MALFORMED_DISCOUNT',
}
